# Generated by Django 4.1.1 on 2022-11-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_user_alter_author_options_alter_book_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('GST', 'Guest'), ('CST', 'Customer'), ('USR', 'User'), ('ADM', 'Admin')], max_length=3),
        ),
    ]
